#!/usr/bin/env ruby

puts "*********************************************Installing********************************************"

puts "Creating files"
$files = ["#{Dir.home}/Documents/personal", "#{Dir.home}/.config"].map { |path| File.new(path) }
puts "You successfully created the following files: [#{$files}]" unless $files.empty?
puts "---------------------------------------------------------------------------------------------------"

$personal_path = "#{Dir.home}/Documents/personal"

puts "Cloning your dotfiles"
`git clone https://github.com/7hoenix/dotfiles.git #{$personal_path}/dotfiles`
puts "You successfuly cloned down github into #{$personal_path}/dotfiles" if File.exist?("#{$personal_path}/dotfiles")
puts "---------------------------------------------------------------------------------------------------"

$dotfiles_path = "#{personal_path}/dotfiles"


def create_symlink(source, destination)
  File.symlink(source, destination)
  if File.symlink(destination)
    puts "Source: #{source}, destination: #{destination}. Created"
  end
end

puts "Creating symlinks"
[["#{$dotfiles_path}/nvim", "#{Dir.home}/.config/nvim"],
 ["#{$dotfiles_path}/fish", "#{Dir.home}/.config/fish"],
 ["#{$dotfiles_path}/tmux/tmux.conf", "#{Dir.home}/.tmux.conf"]].each { |s, d| create_symlink(s, d) }
puts "---------------------------------------------------------------------------------------------------"

puts "Installing Homebrew"
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
`brew update`
`brew upgrade`
puts "---------------------------------------------------------------------------------------------------"

puts "Installing fish"
`brew install fish`
puts "---------------------------------------------------------------------------------------------------"

puts "# sudo echo "/usr/local/bin/fish" > /etc/shells" +
     "# sudo chsh -s /usr/local/bin/fish 7hoenix"
