#!/usr/bin/env ruby

puts "before"
require "fileutils"

# "Documents/personal/dotfiles/nvim"

$file_path = "/Users/jphoenx"
directories = ["/Documents/personal", "/.config"]
symlinkables = [
  ["#{$file_path}/Documents/personal/dotfiles/nvim", "#{$file_path}/.config/nvim"],
  ["#{$file_path}/Documents/personal/dotfiles/fish", "#{$file_path}/.config/fish"],
  ["#{$file_path}/Documents/personal/dotfiles/tmux/tmux.conf", "#{$file_path}/.tmux.conf"]
]

def create_directory(url)
puts "pie"
  if !File.exist? "#{$file_path}/#{url}"
    FileUtils.mkdir "#{$file_path}/#{url}"
  end
end

def create_symlink(source, destination)
puts "cake"
  if !File.exist? destination
    FileUtils.ln_s source, destination
  end
end

directories.each { |url| create_directory(url) }
`git clone https://github.com/7hoenix/dotfiles #{$file_path}/Documents/personal/dotfiles`
symlinkables.each { |s, d| create_symlink(s, d) }

# curl brew install
# brew install fish
# sudo echo "/usr/local/bin/fish" > /etc/shells
# sudo chsh -s /usr/local/bin/fish jphoenix
puts "after"
